# Generated by Django 5.0.6 on 2024-09-11 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portalrequirements',
            old_name='branding_logo',
            new_name='file_image',
        ),
        migrations.RenameField(
            model_name='templatedata',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='templatedata',
            name='domain',
        ),
        migrations.AddField(
            model_name='templatedata',
            name='status',
            field=models.CharField(default='Available', max_length=255),
        ),
        migrations.AlterField(
            model_name='portalrequirements',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_requirement', to='portals.domainregistration'),
        ),
        migrations.AlterField(
            model_name='portalrequirements',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
