# Generated by Django 5.0.6 on 2024-09-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_alter_templatedata_commercial_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalrequirements',
            name='domain',
        ),
        migrations.AlterField(
            model_name='domainregistration',
            name='registration_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainregistration',
            name='registration_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='domainregistration',
            name='registration_status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domainregistration',
            name='registration_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
