# Generated by Django 5.0.6 on 2024-09-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_category_created_at_domainregistration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portals',
            name='domain_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='portals.domainregistration'),
        ),
        migrations.AlterField(
            model_name='portals',
            name='requirement_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='portals.portalrequirements'),
        ),
        migrations.AlterField(
            model_name='portals',
            name='template_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='portals.templatedata'),
        ),
    ]
