# Generated by Django 5.0.6 on 2024-09-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_alter_portals_domain_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portals',
            name='current_step',
            field=models.IntegerField(default=0),
        ),
    ]
