# Generated by Django 5.0.6 on 2024-07-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
