# Generated by Django 5.0.6 on 2024-07-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_customer_id_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
