# Generated by Django 5.0.6 on 2024-06-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password_expires',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token_expires',
        ),
    ]
