# Generated by Django 5.0.6 on 2024-06-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='gallery_images')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, unique=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='stela-editor/main-image/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stela-editor/thumbnail/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('redirect_url', models.URLField(blank=True, null=True, verbose_name='Redirect URL')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, unique=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='stela-editor/main-image/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stela-editor/thumbnail/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('redirect_url', models.URLField(blank=True, null=True, verbose_name='Redirect URL')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, unique=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='stela-editor/main-image/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stela-editor/thumbnail/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('redirect_url', models.URLField(blank=True, null=True, verbose_name='Redirect URL')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(blank=True, to='content.image')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='InfoComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bullet', models.CharField(max_length=255, verbose_name='Title')),
                ('content_bullet', models.TextField(verbose_name='Content')),
                ('numbers', models.IntegerField(default=0, null=True)),
                ('icons', models.CharField(max_length=255, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='content.section')),
            ],
            options={
                'verbose_name': 'Info Component',
                'verbose_name_plural': 'Info Component',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.section'),
        ),
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.FileField(upload_to='files/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.section')),
            ],
            options={
                'verbose_name': 'File Storage',
                'verbose_name_plural': 'Files Storage',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('video', models.FileField(upload_to='video/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.section')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
