# Generated by Django 5.0.6 on 2024-05-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infocomponent',
            name='content',
            field=models.TextField(default='content', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocomponent',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
