# Generated by Django 5.0.6 on 2024-08-25 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicfield',
            old_name='textfield',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='dynamicfield',
            old_name='charfield',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='simplecontent',
            old_name='textfield',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='simplecontent',
            old_name='charfield',
            new_name='options',
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simplecontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simplecontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
