# Generated by Django 5.0.6 on 2024-05-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('No Data', 'No Data'), ('About V1', 'About V1'), ('Content V1', 'Content V1'), ('Experience V1', 'Experience V1'), ('Info Cards V1', 'Info Cards V1'), ('Portfolio V1', 'Portfolio V1'), ('Simple Content V1', 'Simple Content V1'), ('Slider V1', 'Slider V1')], default='No Data', max_length=255),
        ),
        migrations.AddField(
            model_name='gallery',
            name='section',
            field=models.CharField(choices=[('No Data', 'No Data'), ('About V1', 'About V1'), ('Content V1', 'Content V1'), ('Experience V1', 'Experience V1'), ('Info Cards V1', 'Info Cards V1'), ('Portfolio V1', 'Portfolio V1'), ('Simple Content V1', 'Simple Content V1'), ('Slider V1', 'Slider V1')], default='No Data', max_length=255),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='section',
            field=models.CharField(choices=[('No Data', 'No Data'), ('About V1', 'About V1'), ('Content V1', 'Content V1'), ('Experience V1', 'Experience V1'), ('Info Cards V1', 'Info Cards V1'), ('Portfolio V1', 'Portfolio V1'), ('Simple Content V1', 'Simple Content V1'), ('Slider V1', 'Slider V1')], default='No Data', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='section',
            field=models.CharField(choices=[('No Data', 'No Data'), ('About V1', 'About V1'), ('Content V1', 'Content V1'), ('Experience V1', 'Experience V1'), ('Info Cards V1', 'Info Cards V1'), ('Portfolio V1', 'Portfolio V1'), ('Simple Content V1', 'Simple Content V1'), ('Slider V1', 'Slider V1')], default='No Data', max_length=255),
        ),
    ]
