# Generated by Django 5.0.6 on 2024-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_textfield_dynamicfield_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='urlfield',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simplecontent',
            name='urlfield',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
