# Generated by Django 5.0.6 on 2024-05-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_content_infocomponent_content_bullet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stela-editor/thumbnail/'),
        ),
        migrations.AddField(
            model_name='section',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stela-editor/thumbnail/'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stela-editor/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='stela-editor/main-image/'),
        ),
        migrations.AlterField(
            model_name='infocomponent',
            name='icons',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infocomponent',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='content.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='stela-editor/main-image/'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='stela-editor/main-image/'),
        ),
    ]
