# Generated by Django 5.0.6 on 2024-08-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_dynamicfield_urlfield_simplecontent_urlfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='doc',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='image',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='simplecontent',
            name='doc',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='simplecontent',
            name='image',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
