# Generated by Django 5.0.6 on 2024-05-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_article_thumbnail_section_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
