# Generated by Django 5.0.6 on 2024-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_dynamicfield_doc_dynamicfield_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='child_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
