# Generated by Django 5.0.6 on 2024-08-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_dynamicfield_child_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfield',
            name='child_id',
        ),
    ]
