# Generated by Django 5.0.6 on 2024-08-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_dynamicfield_child_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfield',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='dynamicfield',
            name='image',
        ),
        migrations.RemoveField(
            model_name='simplecontent',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='simplecontent',
            name='image',
        ),
        migrations.AlterField(
            model_name='simplecontent',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
