# Generated by Django 5.0.6 on 2024-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
