# Generated by Django 5.1.2 on 2024-11-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_customer_order_billingitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
