# Generated by Django 5.0.6 on 2024-08-24 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('amount_remaining', models.IntegerField(default=0)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('legal_entity', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=500, null=True)),
                ('url_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('transaction_type', models.CharField(default='purchase', max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('setup_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('annually', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('last_4_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=255, null=True)),
                ('funding', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='Free', max_length=100)),
                ('plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('coupon_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
