# Generated by Django 5.0.6 on 2024-07-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
