# Generated by Django 5.0.6 on 2024-07-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentintent_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentintent',
            name='customer_id',
        ),
    ]
