# Generated by Django 5.0.6 on 2024-07-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_checkoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='unix_expires',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
