# Generated by Django 5.0.6 on 2024-07-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_checkoutsession_unix_expires'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutSession',
        ),
    ]
