# Generated by Django 5.0.6 on 2024-07-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_delete_checkoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='setup_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
