# Generated by Django 5.0.6 on 2024-07-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_paymentintent_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethods',
            old_name='last_four_digits',
            new_name='last_4_digits',
        ),
    ]
