# Generated by Django 5.0.6 on 2024-07-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_rename_last_four_digits_paymentmethods_last_4_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
