# Generated by Django 5.0.6 on 2024-07-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_paymentmethods_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='funding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
