# Generated by Django 5.0.6 on 2024-07-31 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_paymentmethods_funding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_off', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(choices=[('repeating', 'Repeating'), ('single_use', 'Single Use')], default='single_use', max_length=50)),
                ('duration_in_months', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('first_time_transaction', models.BooleanField(default=False)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_amount_currency', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.coupon'),
        ),
    ]
