# Generated by Django 5.0.6 on 2024-08-02 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_delete_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='payment_method',
            new_name='control_id',
        ),
        migrations.RenameField(
            model_name='billing',
            old_name='stripe_customer_id',
            new_name='legal_entity',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='subscription',
        ),
        migrations.AddField(
            model_name='billing',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billing',
            name='amount_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billing',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billing',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
