# Generated by Django 5.0.6 on 2024-08-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_rename_payment_method_billing_control_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='url_pdf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
