# Generated by Django 5.0.6 on 2024-06-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_service_rename_quantity_variant_stock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategoria',
            new_name='SubCategory',
        ),
    ]
