# Generated by Django 5.0.6 on 2024-06-07 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_categoria_principal_subcategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategories',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basecategories', to='inventory.subcategories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.basecategories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Inactivo', max_length=255),
        ),
    ]
