# Generated by Django 5.0.6 on 2024-06-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_basecategories_parent_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
