# Generated by Django 5.0.6 on 2024-06-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_service_status_alter_servicevariant_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='inventory.category'),
        ),
    ]
