# Generated by Django 5.0.6 on 2024-06-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_service_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicevariant',
            name='duration',
        ),
    ]
