# Generated by Django 5.0.6 on 2024-06-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevariant',
            name='status',
            field=models.CharField(default='Inactivo', max_length=255),
        ),
        migrations.AddField(
            model_name='variant',
            name='status',
            field=models.CharField(default='Inactivo', max_length=255),
        ),
    ]
