# Utiliza la imagen de Python 3.9 como base
FROM python:3.10.6-slim-buster

WORKDIR /app

COPY . /app

COPY .env /app/core/settings/.env

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

CMD ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "1", "--timeout", "300"]
