org: emmerut
app: stelaux
service: stelaux-api

provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: us-east-1

functions:
  api_handler:
    handler: handler.api_handler
    events:
      - http:
          path: '/'
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: handler.application

  pythonRequirements:
    zip: true
    slim: true
    fileName: requirements.txt

package:
  exclude:
    - .serverless/**
    - .venv/**
    - node_modules/**
    - requirements/**

